framework:
    notifier:
        chatter_transports:
        texter_transports:
            email: smtp://%env(MAILER_DSN)%
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            '': ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: michal@mleczko.dev }
