novaway_feature_flag:
  default_manager: default
  managers:
    default:
      factory: 'novaway_feature_flag.factory.array'
      options:
        features:
          cart: false

when@test:
  novaway_feature_flag:
    managers:
      default:
        options:
          features:
            manual_bookings: true
