swoole:
  http_server:
    static: advanced
    services:
      trust_all_proxies_handler: true
    trusted_proxies: '*'
  task_worker:
    services:
      reset_handler: true
    settings:
      worker_count: auto