framework:
    workflows:
        booking:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Booking
            initial_marking: pending
            places:
                - pending
                - confirmed
                - cancelled
                - completed
                - refund_requested
            transitions:
                confirm:
                    guard: "subject.canBeConfirmed()"
                    from: pending
                    to: confirmed
                cancel:
                    guard: "subject.canBeCancelled()"
                    from: [pending, confirmed]
                    to: cancelled
                request_refund:
                    guard: "subject.canRequestRefund()"
                    from: [pending, confirmed]
                    to: refund_requested
                complete:
                    guard: "subject.canBeCompleted()"
                    from: confirmed
                    to: completed
                reschedule:
                    guard: "subject.canBeRescheduled()"
                    from: [pending, confirmed]
                    to: cancelled
                    metadata:
                        new_booking_required: true
                        reason: 'rescheduled'

        payment:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Payment
            initial_marking: pending
            places:
                - pending
                - paid
                - failed
                - refunded
                - expired
            transitions:
                pay:
                    guard: "subject.isPaid() or is_granted('ROLE_ADMIN')"
                    from: pending
                    to: paid
                fail:
                    from: pending
                    to: failed
                refund:
                    from: paid
                    to: refunded
                expire:
                    from: pending
                    to: expired
