services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - .:/app
      - ~/.composer:/.composer
    working_dir: /app
    command: bin/console swoole:server:run
    user: 1000:1000
    ports:
      - "9501:9501"
