services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      target: dev-local
    environment:
      COMPOSER_HOME: /.composer
      PHP_CS_FIXER_IGNORE_ENV: true
    volumes:
      - .:/app
      - ~/.composer:/.composer
    user: 1000:1000
    ports:
      - "9501:9501"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: ~
