services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      COMPOSER_HOME: /.composer
      PHP_CS_FIXER_IGNORE_ENV: true
    volumes:
      - .:/app
      - ~/.composer:/.composer
    user: 1000:1000
    ports:
      - "9501:9501"
