<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Extracts LessonMetadata from an embedded value duplicated on every Lesson
 * row into its own table, referenced by FK — so occurrences sharing the
 * same content (as generated by ExtendSeriesScheduleHandler) can share one
 * row instead of each carrying a full copy. Existing lesson rows get their
 * own 1:1 lesson_metadata row (reusing the lesson's own id), preserving all
 * current data exactly; future rows may share a metadata row across several
 * lessons.
 */
final class Version20260810210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Extract LessonMetadata into its own table, referenced by lesson.metadata_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lesson_metadata (id UUID NOT NULL, title VARCHAR(255) NOT NULL, lead TEXT NOT NULL, visual_theme VARCHAR(255) NOT NULL, description TEXT NOT NULL, capacity INT NOT NULL, duration INT NOT NULL, category VARCHAR(50) NOT NULL, slug VARCHAR(255) DEFAULT NULL, image_data TEXT DEFAULT NULL, image_mime_type VARCHAR(100) DEFAULT NULL, age_range_min INT NOT NULL, age_range_max INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN lesson_metadata.id IS \'(DC2Type:ulid)\'');

        // One lesson_metadata row per existing lesson (reusing the lesson's
        // own id keeps the link trivial and collision-free); future code
        // decides when to share a row across lessons.
        $this->addSql('INSERT INTO lesson_metadata (id, title, lead, visual_theme, description, capacity, duration, category, slug, image_data, image_mime_type, age_range_min, age_range_max)
            SELECT id, title, lead, visual_theme, description, capacity, duration, category, slug, image_data, image_mime_type, age_range_min, age_range_max FROM lesson');

        $this->addSql('ALTER TABLE lesson ADD metadata_id UUID DEFAULT NULL');
        $this->addSql('UPDATE lesson SET metadata_id = id');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN metadata_id SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN lesson.metadata_id IS \'(DC2Type:ulid)\'');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_LESSON_METADATA FOREIGN KEY (metadata_id) REFERENCES lesson_metadata (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_LESSON_METADATA_ID ON lesson (metadata_id)');

        $this->addSql('ALTER TABLE lesson DROP title');
        $this->addSql('ALTER TABLE lesson DROP lead');
        $this->addSql('ALTER TABLE lesson DROP visual_theme');
        $this->addSql('ALTER TABLE lesson DROP description');
        $this->addSql('ALTER TABLE lesson DROP capacity');
        $this->addSql('ALTER TABLE lesson DROP duration');
        $this->addSql('ALTER TABLE lesson DROP category');
        $this->addSql('ALTER TABLE lesson DROP slug');
        $this->addSql('ALTER TABLE lesson DROP image_data');
        $this->addSql('ALTER TABLE lesson DROP image_mime_type');
        $this->addSql('ALTER TABLE lesson DROP age_range_min');
        $this->addSql('ALTER TABLE lesson DROP age_range_max');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lesson ADD title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD lead TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD visual_theme VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD capacity INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD duration INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD category VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD image_data TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD image_mime_type VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD age_range_min INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lesson ADD age_range_max INT DEFAULT NULL');

        $this->addSql('UPDATE lesson l SET title = m.title, lead = m.lead, visual_theme = m.visual_theme, description = m.description, capacity = m.capacity, duration = m.duration, category = m.category, slug = m.slug, image_data = m.image_data, image_mime_type = m.image_mime_type, age_range_min = m.age_range_min, age_range_max = m.age_range_max FROM lesson_metadata m WHERE m.id = l.metadata_id');

        $this->addSql('ALTER TABLE lesson ALTER COLUMN title SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN lead SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN visual_theme SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN description SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN capacity SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN duration SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN category SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN age_range_min SET NOT NULL');
        $this->addSql('ALTER TABLE lesson ALTER COLUMN age_range_max SET NOT NULL');

        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_LESSON_METADATA');
        $this->addSql('DROP INDEX IDX_LESSON_METADATA_ID');
        $this->addSql('ALTER TABLE lesson DROP metadata_id');
        $this->addSql('DROP TABLE lesson_metadata');
    }
}
