<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260810082931 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align schema with DBAL 4 / DoctrineBundle 3: drop legacy type comments and convert SERIAL id columns to native IDENTITY, preserving existing sequence values.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON COLUMN activity_log.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN activity_log.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.child_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.payment_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.lessons_map IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking.approved_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking_lesson.booking_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN booking_lesson.lesson_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN child.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN child.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN child.birthday IS \'\'');
        $this->addSql('COMMENT ON COLUMN finance_contact.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN finance_contact.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN lesson.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN lesson.series_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN lesson.ticket_options IS \'\'');
        $this->addSql('COMMENT ON COLUMN lesson.schedule IS \'\'');
        $this->addSql('COMMENT ON COLUMN lesson_instructor.lesson_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN notification.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN notification.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notification.read_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notification.deleted_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.paid_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.amount IS \'\'');
        // Converting SERIAL to IDENTITY: DROP DEFAULT alone leaves the old sequence
        // orphaned-but-still-OWNED-BY the column, so ADD GENERATED AS IDENTITY creates
        // a *second*, differently-named sequence starting at 1 rather than reusing it
        // (verified: pg_get_serial_sequence() then resolves to the stale orphaned one,
        // not the new identity sequence). Dropping the old sequence first frees its name
        // for the new identity sequence, and RESTART WITH reseeds it past existing rows
        // to avoid a primary key collision on the next insert.
        $this->addSql('ALTER TABLE payment_code ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE payment_code_id_seq');
        $this->addSql('ALTER TABLE payment_code ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN payment_code.payment_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment_code.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN series.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN series.ticket_options IS \'\'');
        $this->addSql('COMMENT ON COLUMN series_instructor.series_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN setting.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN setting.content IS \'\'');
        $this->addSql('ALTER TABLE transfer ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE transfer_id_seq');
        $this->addSql('ALTER TABLE transfer ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN transfer.payment_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN transfer.transferred_at IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE user_id_seq');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN "user".phone IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".confirmed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".newsletter_consent_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_messages.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_messages.related_booking_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_messages.related_lesson_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_messages.read_at IS \'\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');

        // Reseed each new identity sequence past the table's current MAX(id) so the
        // next insert doesn't collide with existing rows (verified via reproduction:
        // a freshly-created identity sequence otherwise starts at 1).
        $this->addSql(<<<'SQL'
            DO $$
            DECLARE
                next_id bigint;
            BEGIN
                SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM payment_code;
                EXECUTE format('ALTER TABLE payment_code ALTER COLUMN id RESTART WITH %s', next_id);

                SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM transfer;
                EXECUTE format('ALTER TABLE transfer ALTER COLUMN id RESTART WITH %s', next_id);

                SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM "user";
                EXECUTE format('ALTER TABLE "user" ALTER COLUMN id RESTART WITH %s', next_id);

                SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM messenger_messages;
                EXECUTE format('ALTER TABLE messenger_messages ALTER COLUMN id RESTART WITH %s', next_id);
            END $$
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON COLUMN activity_log.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN activity_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN booking.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN booking.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN booking.lessons_map IS \'(DC2Type:lesson_map)\'');
        $this->addSql('COMMENT ON COLUMN booking.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN booking.approved_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN booking.child_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN booking.payment_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN booking_lesson.booking_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN booking_lesson.lesson_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN child.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN child.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN child.birthday IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN finance_contact.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN finance_contact.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lesson.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN lesson.ticket_options IS \'(DC2Type:json_document)\'');
        $this->addSql('COMMENT ON COLUMN lesson.schedule IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lesson.series_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN lesson_instructor.lesson_id IS \'(DC2Type:ulid)\'');
        // DROP IDENTITY must come before recreating the plain-sequence default: Postgres
        // rejects SET DEFAULT while the column is still an identity column, and DROP
        // IDENTITY itself drops the identity's sequence (verified via reproduction), so
        // the old sequence needs recreating rather than just reattaching.
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE messenger_messages_id_seq OWNED BY messenger_messages.id');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql("SELECT setval('messenger_messages_id_seq', COALESCE((SELECT MAX(id) FROM messenger_messages), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notification.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN notification.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notification.read_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notification.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN payment.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment.paid_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment.amount IS \'(DC2Type:json_document)\'');
        $this->addSql('ALTER TABLE payment_code ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE payment_code_id_seq OWNED BY payment_code.id');
        $this->addSql('ALTER TABLE payment_code ALTER id SET DEFAULT nextval(\'payment_code_id_seq\'::regclass)');
        $this->addSql("SELECT setval('payment_code_id_seq', COALESCE((SELECT MAX(id) FROM payment_code), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN payment_code.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment_code.payment_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN series.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN series.ticket_options IS \'(DC2Type:json_document)\'');
        $this->addSql('COMMENT ON COLUMN series_instructor.series_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN setting.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN setting.content IS \'(DC2Type:json_document)\'');
        $this->addSql('ALTER TABLE transfer ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE transfer_id_seq OWNED BY transfer.id');
        $this->addSql('ALTER TABLE transfer ALTER id SET DEFAULT nextval(\'transfer_id_seq\'::regclass)');
        $this->addSql("SELECT setval('transfer_id_seq', COALESCE((SELECT MAX(id) FROM transfer), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN transfer.transferred_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN transfer.payment_id IS \'(DC2Type:ulid)\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE user_id_seq OWNED BY "user".id');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('SELECT setval(\'user_id_seq\', COALESCE((SELECT MAX(id) FROM "user"), 0) + 1, false)');
        $this->addSql('COMMENT ON COLUMN "user".phone IS \'(DC2Type:phone_number)\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".confirmed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".newsletter_consent_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_messages.id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN user_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_messages.read_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_messages.related_booking_id IS \'(DC2Type:ulid)\'');
        $this->addSql('COMMENT ON COLUMN user_messages.related_lesson_id IS \'(DC2Type:ulid)\'');
    }
}
