name: Build and QA

on:
  push:
    branches:
      - master

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-qa:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and tag Docker image with cache
      - name: Build and tag Docker image
        run: |
          docker build \
            --cache-from=type=registry,ref=$GHCR_IMAGE:cache \
            --cache-to=type=inline \
            -t $GHCR_IMAGE:latest \
            --file .docker/php/Dockerfile \
            --target dev .

      # Run Composer QA script
      - name: Run Composer QA
        run: docker run --rm $GHCR_IMAGE composer qa

      # Push Docker image and cache to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push $GHCR_IMAGE:latest
          docker push $GHCR_IMAGE:cache