name: Build and QA

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-qa:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Composer QA script
      - name: Run Composer QA
        run: docker compose run --rm php composer qa