name: Build and QA

on:
  push:
    branches:
      - master
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-qa:
    outputs:
      image_digest: ${{ steps.image-digest.outputs.image_digest }}
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: "!ChangeMe!"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app -d app_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long

      # Build and cache development image
      - name: Build and cache development image
        id: build-dev
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/php/Dockerfile
          target: dev
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-cache
          cache-to: ${{ github.event_name == 'push' && format('type=registry,ref={0}/{1}:dev-cache,mode=max', env.REGISTRY, env.IMAGE_NAME) || '' }}
          load: true

      # Run Composer Static Analysis script against the development image
      - name: Run Composer SA
        run: docker run --rm ${{ steps.meta.outputs.tags }} composer sa


      - name: Get GitHub Actions Docker network name
        id: network
        run: |
            echo "NETWORK_NAME=$(docker network ls --filter name=github --format '{{.Name}}')" >> $GITHUB_ENV

      # Run all tests
      - name: Run Tests
        run: docker run --rm --network $NETWORK_NAME ${{ steps.meta.outputs.tags }} composer tests
        env:
          DATABASE_URL: "postgresql://app:!ChangeMe!@db:5432/app_test?serverVersion=15&charset=utf8"

      - name: Extract production metadata
        if: success()
        id: meta-prod
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long

      - name: Generate version
        id: version
        run: |
          export TZ="Europe/Warsaw"
          echo "APP_VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      # Build and push production image if QA passes (only on push to main)
      - name: Build and push production image
        uses: actions-ecosystem/action-push-tag@v1
        if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/master')
        with:
          tag:
            ${{ steps.version.outputs.APP_VERSION }}
