name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and QA"]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    environment: production
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    outputs:
      image_digest: ${{ steps.image-ref.outputs.image_digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get image reference
        id: image-ref
        run: |
          # Get the image reference from the build job or use latest tag
          if [ -n "${{ needs.build-and-qa.outputs.image_digest }}" ]; then
            IMAGE_REF="${{ needs.build-and-qa.outputs.image_digest }}"
            echo "Using image digest from build job: $IMAGE_REF"
          else
            IMAGE_REF="ghcr.io/${{ github.repository }}:sha-${{ github.sha }}"
            echo "Warning: Could not get image digest from build job, falling back to latest tag: $IMAGE_REF"
          fi
          
          # Set the output
          echo "image_digest=$IMAGE_REF" >> $GITHUB_OUTPUT

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/projects/hosting/
            
            # Get the image reference from previous step
            IMAGE_REF="${{ steps.image-ref.outputs.image_digest }}"
            
            # Update .env file with the new image reference
            echo "Updating .env file with new image reference..."
            if [ ! -f .env ]; then
              touch .env
            fi
            
            # Add or update KIDDO_IMAGE in .env
            if grep -q '^KIDDO_IMAGE=' .env; then
              sed -i "s|^KIDDO_IMAGE=.*|KIDDO_IMAGE=$IMAGE_REF|" .env
            else
              echo "KIDDO_IMAGE=$IMAGE_REF" >> .env
            fi
            
            # Pull the latest image
            echo "Pulling the latest Docker image..."
            echo "Using image reference: $IMAGE_REF"
            
            # Login to GitHub Container Registry if using ghcr.io
            if [[ $IMAGE_REF == ghcr.io/* ]]; then
              echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            fi
            
            docker compose pull kiddo 
            
            # Run the new container with the updated image
            echo "Starting new container..."
            docker compose up -d kiddo
            
            # Run database migrations
            echo "Running database migrations..."
            docker compose exec kiddo bin/console doctrine:schema:update --force --no-interaction
            
            echo "Deployment completed successfully!"
