name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and QA"]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest image tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/projects/hosting/
            
            # Pull the latest image
            echo "Pulling the latest Docker image..."
            docker pull ${{ steps.meta.outputs.tags }}
            
            # Stop and remove the existing container if it's running
            if docker ps -a --format '{{.Names}}' | grep -q '^kiddo$'; then
              echo "Stopping and removing existing container..."
              docker stop kiddo || true
              docker rm kiddo || true
            fi
            
            # Run the new container with the updated image
            echo "Starting new container..."
            docker run -d \
              --name kiddo \
              --restart unless-stopped \
              -p 80:80 \
              -v /path/to/your/.env:/app/.env \
              -v /path/to/your/var:/app/var \
              ${{ steps.meta.outputs.tags }}
            
            # Wait for the container to be ready
            echo "Waiting for container to be ready..."
            sleep 10
            
            # Run database migrations
            echo "Running database migrations..."
            docker exec kiddo php bin/console doctrine:schema:update --force --no-interaction
            
            echo "Deployment completed successfully!"
          env:
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
